blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://docs.layerai.yun
    about: Install, features, and troubleshooting
  - name: Website
    url: https://layerai.yun/
    about: Product overview, pricing, and subscription
